In [1]:
import numpy as np

## Creating array from list (i.e converting python list to numpy array)

In [2]:
list = [2,4,6,8,10]
arr = np.array(list)
print(arr)

arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array:",arr_2d)

[ 2  4  6  8 10]
1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [3]:
py_list = [1,2,3]
print("\n Python list multiplication:", py_list * 2)

np_array = np.array([1,2,3]) #each element multiplication
print("\n Numpy array multiplication:", np_array * 2)

import time as t
start = t.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ", t.time() - start)

start = t.time()
np_array = np.arange(1000000) * 2
print("\n Numpy array operation time: ", t.time() - start)


 Python list multiplication: [1, 2, 3, 1, 2, 3]

 Numpy array multiplication: [2 4 6]

 List operation time:  0.09416747093200684

 Numpy array operation time:  0.009480476379394531


## Creating Array from scratch

In [13]:
zerosArray = np.zeros((3,4)) #Zeros Array
print("Zeros Array: \n", zerosArray)

onesArray = np.ones((3,4)) #Ones Array
print("Ones Array: \n", onesArray)

customFullArray = np.full((3,4), 8) #Custom Full Array
print("Custom Full Array: \n", customFullArray)

randomValueArray = np.random.random((2,3)) #Random Value Array
print("Random Value Array: \n", randomValueArray)

sequenceRangeArray = np.arange(0, 10, 2) #Sequence Range Array. It always returns 1D array =====> .arange(start, stop, step)
print("Sequence Range Array: \n", sequenceRangeArray)

linSpaceArray = np.linspace(1,6,5) #Linespace Array. Returns 1D Array. Difference between each two elements are equal on subtraction =====> .linspace(start, end, numberOfElements)
print(f"linspace Array: \n {linSpaceArray}")

Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Custom Full Array: 
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
Random Value Array: 
 [[0.98833981 0.82043142 0.23869037]
 [0.00661342 0.14109876 0.33249265]]
Sequence Range Array: 
 [0 2 4 6 8]
linspace Array: 
 [1.   2.25 3.5  4.75 6.  ]


## Vector, Matrix & Tensor

In [ ]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3], 
                   [4,5,6]]) #2D arrays
print("Matrix: \n", matrix)

tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) #3D or arrays more than 3 dimension
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array Properties

In [ ]:
arr = np.array([[1,2,3], [4,5,6.1]])

print("Shape:", arr.shape) #shape/form of the array
print("Dimension:", arr.ndim) #number of dimension of the array
print("Size:", arr.size) #total number of elements in the array
print("DataType:", arr.dtype) #datatype of the array (most often similar datatype is used)

Shape: (2, 3)
Dimension: 2
Size: 6
DataType: float64


## Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array: \n",arr)

#Reshaping the Array
reshapedArray = arr.reshape((3,4))
print("Reshaped Array: \n", reshapedArray)

#Flattening the Array (to 1D Array). Returns copy of the original array
flattenedArray = arr.flatten()
print("Flattened Array: \n", flattenedArray)

#Ravel the Array (to 1D Array). Returns view instead of copy of the original array
#A view means that the returned array shares the same memory as the original array
#Therefore, changes made to the array returned by ravel() will also affect the original array.
#If a view cannot be returned (e.g., due to non-contiguous memory layout), ravel() will return a copy. 
raveledArray = arr.ravel()
print("Raveled Array: \n", raveledArray)

#Transpose of the Array (convert a column element to a row element and vice versa of the specified array i.e here we are taking reshapedArray)
transposedArray = reshapedArray.transpose()
print("Transposed Array: \n", transposedArray)

Original Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
