## Numpy Array Operations

In [1]:
import numpy as np

## Slicing

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing:", arr[2])
print("with [start:stop] Slicing:", arr[2:7])
print("with [start:stop:step] Slicing:", arr[1:8:2])
print("Negative Index Slicing:", arr[-3])

Basic Slicing: 3
with [start:stop] Slicing: [3 4 5 6 7]
with [start:stop:step] Slicing: [2 4 6 8]
Negative Index Slicing: 8


In [28]:
arr = np.random.randint(0, 49, size=100).reshape(4,5,5)
print(arr)

[[[ 6 42 31 14 23]
  [22 20 44 39 19]
  [34  4 22 26  2]
  [15 11  0 40  7]
  [15 25 10 46 10]]

 [[39 11 37 15  2]
  [39 22 24 47 24]
  [15  7 26  9 11]
  [28 43  6 18 24]
  [19 37 17  9 48]]

 [[16 29 16 16 41]
  [16 42 26 25 17]
  [ 5 34 37 28 34]
  [30  9 22 23  4]
  [16 13 27 32 32]]

 [[16 46  4 18  3]
  [29 28  0 23 32]
  [34 42 25  6  4]
  [19 17  3 42 22]
  [27 48 40  5 40]]]


In [45]:
print("slicing the 3d array: \n",arr[2:, 2:4, 2:], "\n")

print("selecting 1 element: ",arr[2,3,4])

slicing the 3d array: 
 [[[37 28 34]
  [22 23  4]]

 [[25  6  4]
  [ 3 42 22]]] 

selecting 1 element:  4


## Select element, row (start with 0th index) & column (start with 0th index)

In [3]:
arr_2D = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])

print("Specific element:", arr_2D[2,1]) #array[row,column]
print("Entire Row: \n", arr_2D[2]) #array[row]
print("Entire Column: \n", arr_2D[:,1]) #array[:,column] ====> : refers to every row

Specific element: 8
Entire Row: 
 [7 8 9]
Entire Column: 
 [2 5 8]


## Sorting

In [4]:
array_1D_unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array: \n", np.sort(array_1D_unsorted))

array_2D_unsorted = np.array([[50,10], 
                              [40,60], 
                              [30,20]])
print("Sorted 2D Array by Column (axis = 0): \n", np.sort(array_2D_unsorted, axis = 0))
print("Sorted 2D Array by Row (axis = 1): \n", np.sort(array_2D_unsorted, axis = 1))

Sorted Array: 
 [1 1 2 3 4 5 6 9]
Sorted 2D Array by Column (axis = 0): 
 [[30 10]
 [40 20]
 [50 60]]
Sorted 2D Array by Row (axis = 1): 
 [[10 50]
 [40 60]
 [20 30]]


## Filtering

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_number = numbers[numbers % 2 == 0]
print("Even Numbers: \n", even_number)

Even Numbers: 
 [ 2  4  6  8 10]


## Filtering with Mask

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

mask = numbers > 5
print("Number greater than 5: \n", numbers[mask])

indices = [0,2,4]
print("Numbers on indices position: \n", numbers[indices])

Number greater than 5: 
 [ 6  7  8  9 10]
Numbers on indices position: 
 [1 3 5]


## Fancy Indexing vs np.where()

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

#np.where(condition)
where_result = np.where(numbers > 5)
print(f"NP where: \n {numbers[where_result]} \n", )

condition_array = np.where(numbers > 5, "greater than 5 (else-if)", "small (else)")
print("Condition Array: \n", condition_array)

NP where: 
 [ 6  7  8  9 10] 

Condition Array: 
 ['small (else)' 'small (else)' 'small (else)' 'small (else)'
 'small (else)' 'greater than 5 (else-if)' 'greater than 5 (else-if)'
 'greater than 5 (else-if)' 'greater than 5 (else-if)'
 'greater than 5 (else-if)']


## Adding and Removing data

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#concatenate multiple arrays
concatenated_array = np.concatenate((arr1, arr2))
print("Concatenated Array: \n", concatenated_array)

Concatenated Array: 
 [1 2 3 4 5 6]


## Array Compatibility

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility Shape between a & b:", a.shape == b.shape)
print("Compatibility Shape between a & c:", a.shape == c.shape)
print("Compatibility Shape between b & c:", b.shape == c.shape)

Compatibility Shape between a & b: False
Compatibility Shape between a & c: True
Compatibility Shape between b & c: False


In [10]:
originalArray = np.array([[1,2], [3,4]])

#.vstack() ====> row-wise (i.e add new row to the original array)
newRow = np.array([[5,6]])
withNewRow = np.vstack((originalArray, newRow))
print("vstack --> with new row: \n", withNewRow)

#.hstack() ====> column-wise (i,e add new column to the original array)
newColumn = np.array([[7],[8]])
withNewColumn = np.hstack((originalArray, newColumn))
print("hstack --> with new column: \n", withNewColumn)

vstack --> with new row: 
 [[1 2]
 [3 4]
 [5 6]]
hstack --> with new column: 
 [[1 2 7]
 [3 4 8]]


## Delete
np.delete(arr, index_of_what_to_delete or slice_if_not_known)

In [11]:
arr = np.arange(1,6,1)
print("Original Array: \n", arr)

array_after_Deletion = np.delete(arr, (0,2,2))
print("Array after deletion: \n", array_after_Deletion)

Original Array: 
 [1 2 3 4 5]
Array after deletion: 
 [2 4 5]
