In [34]:
import numpy as np

In [35]:
# Create a NumPy array of numbers from 10 to 50.
arr1 = np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [36]:
# Generate a 3×3 identity matrix.
idMatrix = np.eye(3,3)
print(idMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# Create a NumPy array of 10 random integers between 1 and 100.
arr2 = np.random.randint(1,100,10)
print(arr2)

[48 40 86 58 69 80 21 97 28 74]


In [38]:
# Find the maximum and minimum of an array.
maximumNumber = np.max(arr2)
minimumNumber = np.min(arr2)
print(f"maximum: {maximumNumber}")
print(f"minimum: {minimumNumber}")

maximum: 97
minimum: 21


In [39]:
# Reshape a 1D array of 12 elements into a 3×4 matrix.
org_arr = np.random.randint(1,100,12)
reshapedArray = np.reshape(org_arr, (3,4))
print(f"reshapedArray: \n {reshapedArray}")

reshapedArray: 
 [[31 30 95 59]
 [12 52 16 49]
 [31 27 87  9]]


In [40]:
# Create an array of all even numbers between 50 and 100.
even_array = np.arange(50,101,2)
print(f"Even Number array between 50 and 100: \n {even_array}")

Even Number array between 50 and 100: 
 [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [41]:
# Given an array Given an array [1,2,3,4,5], compute the square of each element. compute the square of each element.
arr3 = np.array([1,2,3,4,5])
print(arr3)

squaredArray = arr3**2
print(squaredArray)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [42]:
# Create a 5×5 array of random numbers and find its mean.
arr4 = np.random.randint(5,50,(5,5))
print(arr4)

print(f"Mean of the array: {np.mean(arr4)}")

[[33 44 32 13 41]
 [13 14 29 21 25]
 [47 30 25 27 37]
 [47 42 16 23 43]
 [ 5 35 49 13 37]]
Mean of the array: 29.64


In [43]:
# Find the index of the maximum element in [10, 20, 50, 40, 30].
arr5 = np.array([10, 20, 50, 40, 30])
print(f"array5: {arr5}")

maxNum = np.max(arr5)
print(f"Maximum Number in the array: {maxNum}")

index = 0
for i in arr5:
    if i == maxNum:
        break
    else:
        index += 1
print(f"Index of the Maximum Number: {index}")

array5: [10 20 50 40 30]
Maximum Number in the array: 50
Index of the Maximum Number: 2


In [44]:
# Create two arrays and perform element-wise addition, subtraction, multiplication, and division.
first_Array = np.random.randint(1,100,(3,4))
second_Array = np.random.randint(1,100,(3,4))
print(f"first array:\n{first_Array}\n\nsecond array:\n{second_Array}\n")

first array:
[[41 33 62 53]
 [36 64  6 53]
 [56 78  4 48]]

second array:
[[88 92 63 61]
 [24 28 45 49]
 [41 48 82 35]]



In [45]:
multiplication = np.multiply(first_Array, second_Array)
print(f"Multiplication:\n {multiplication}\n")

division = np.divide(first_Array, second_Array)
print(f"Division:\n {division}\n")

addition = np.add(first_Array, second_Array)
print(f"Addition:\n {addition}\n")

subtraction = np.subtract(first_Array, second_Array)
print(f"Subtraction:\n {subtraction}\n")

Multiplication:
 [[3608 3036 3906 3233]
 [ 864 1792  270 2597]
 [2296 3744  328 1680]]

Division:
 [[0.46590909 0.35869565 0.98412698 0.86885246]
 [1.5        2.28571429 0.13333333 1.08163265]
 [1.36585366 1.625      0.04878049 1.37142857]]

Addition:
 [[129 125 125 114]
 [ 60  92  51 102]
 [ 97 126  86  83]]

Subtraction:
 [[-47 -59  -1  -8]
 [ 12  36 -39   4]
 [ 15  30 -78  13]]

