In [1]:
import numpy as np

In [2]:
# Create a NumPy array of numbers from 10 to 50.
arr1 = np.arange(10,51)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [3]:
# Generate a 3×3 identity matrix.
idMatrix = np.eye(3,3)
print(idMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Create a NumPy array of 10 random integers between 1 and 100.
arr2 = np.random.randint(1,100,10)
print(arr2)

[14 89 17 71 98 72 13 97  4 66]


In [5]:
# Find the maximum and minimum of an array.
maximumNumber = np.max(arr2)
minimumNumber = np.min(arr2)
print(f"maximum: {maximumNumber}")
print(f"minimum: {minimumNumber}")

maximum: 98
minimum: 4


In [6]:
# Reshape a 1D array of 12 elements into a 3×4 matrix.
org_arr = np.random.randint(1,100,12)
reshapedArray = np.reshape(org_arr, (3,4))
print(f"reshapedArray: \n {reshapedArray}")

reshapedArray: 
 [[66 32 46 80]
 [58 71 10 19]
 [25 11 74 70]]


In [7]:
# Create an array of all even numbers between 50 and 100.
even_array = np.arange(50,101,2)
print(f"Even Number array between 50 and 100: \n {even_array}")

Even Number array between 50 and 100: 
 [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [8]:
# Given an array Given an array [1,2,3,4,5], compute the square of each element. compute the square of each element.
arr3 = np.array([1,2,3,4,5])
print(arr3)

squaredArray = arr3**2
print(squaredArray)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [9]:
# Create a 5×5 array of random numbers and find its mean.
arr4 = np.random.randint(5,50,(5,5))
print(arr4)

print(f"Mean of the array: {np.mean(arr4)}")

[[13 29 21 42  5]
 [18 38 23 11 31]
 [23 49 25 21 12]
 [49 17  7  9 15]
 [47 29 36  6 45]]
Mean of the array: 24.84


In [10]:
# Find the index of the maximum element in [10, 20, 50, 40, 30].
arr5 = np.array([10, 20, 50, 40, 30])
print(f"array5: {arr5}")

maxNum = np.max(arr5)
print(f"Maximum Number in the array: {maxNum}")

index = 0
for i in arr5:
    if i == maxNum:
        break
    else:
        index += 1
print(f"Index of the Maximum Number: {index}")

array5: [10 20 50 40 30]
Maximum Number in the array: 50
Index of the Maximum Number: 2


In [11]:
# Create two arrays and perform element-wise addition, subtraction, multiplication, and division.
first_Array = np.random.randint(1,100,(3,4))
second_Array = np.random.randint(1,100,(3,4))
print(f"first array:\n{first_Array}\n\nsecond array:\n{second_Array}\n")

first array:
[[78 59 98 94]
 [95 84  6 87]
 [55 13 24 25]]

second array:
[[68 23 41  5]
 [ 2 64 79 54]
 [55 68 82 56]]



In [12]:
multiplication = np.multiply(first_Array, second_Array)
print(f"Multiplication:\n {multiplication}\n")

division = np.divide(first_Array, second_Array)
print(f"Division:\n {division}\n")

addition = np.add(first_Array, second_Array)
print(f"Addition:\n {addition}\n")

subtraction = np.subtract(first_Array, second_Array)
print(f"Subtraction:\n {subtraction}\n")

Multiplication:
 [[5304 1357 4018  470]
 [ 190 5376  474 4698]
 [3025  884 1968 1400]]

Division:
 [[ 1.14705882  2.56521739  2.3902439  18.8       ]
 [47.5         1.3125      0.07594937  1.61111111]
 [ 1.          0.19117647  0.29268293  0.44642857]]

Addition:
 [[146  82 139  99]
 [ 97 148  85 141]
 [110  81 106  81]]

Subtraction:
 [[ 10  36  57  89]
 [ 93  20 -73  33]
 [  0 -55 -58 -31]]

